import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Cetak_Laporan extends javax.swing.JInternalFrame {
    ResultSet rs;
    KoneksiDatabase con;
    public String lap;
    public void cetak() {
        // Membersihkan tampilan sebelum melakukan operasi
        clear();
        // Membuat format tanggal untuk pemilihan rentang tanggal
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String a = String.valueOf(format.format(jDate1.getDate()));
        String b = String.valueOf(format.format(jDate2.getDate())); 
    try {
    // Mengeksekusi query untuk mengambil total dari tb_laporan dalam rentang tanggal tertentu
    rs = con.eksekusiQuery("SELECT SUM(total) FROM tb_laporan WHERE DATE_FORMAT(tgl_peminjaman, '%Y-%m-%d') >= '" + a + "' AND DATE_FORMAT(tgl_peminjaman, '%Y-%m-%d') <= '" + b + "'");
    
    while(rs.next()){
        // Mendapatkan nilai total dari hasil query
        lap = rs.getString(1);
    }
    try {
        // Mencetak tabel_laporan dengan mode FIT_WIDTH dan menambahkan header dengan total transaksi
        tabel_laporan.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat("Data Transaksi dengan Total : Rp. " + lap), null);
    } catch(PrinterException ep) {
        // Menangani exception jika terjadi kesalahan saat mencetak
        JOptionPane.showMessageDialog(null, ep);
    }
    } catch (SQLException es) {
    // Menangani exception jika terjadi kesalahan SQL
    JOptionPane.showMessageDialog(rootPane, "Error " + es);
    }
    }
    public void hitungtotal() {
    // Membuat objek SimpleDateFormat untuk memformat tanggal
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    // Mengambil tanggal dari komponen jDate1 dan jDate2, lalu memformatnya ke dalam string
    String a = String.valueOf(format.format(jDate1.getDate()));
    String b = String.valueOf(format.format(jDate2.getDate())); 
    try {
    // Mengeksekusi query SQL untuk menghitung total dari tb_laporan dalam rentang tanggal tertentu
    rs = con.eksekusiQuery("SELECT SUM(total) FROM tb_laporan WHERE DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')>='"+a+"' AND DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')<= '"+b+"' ");
    // Menggunakan loop while untuk membaca hasil query
    while(rs.next()){
        // Mengambil nilai total dari hasil query
        lap = rs.getString(1);
        // Menetapkan nilai total ke dalam komponen lbl_total
        lbl_total.setText(lap);
    }                
} catch (SQLException es) {
    // Menangani exception jika terjadi kesalahan SQL
    JOptionPane.showMessageDialog(rootPane, "Error " + es);
}
    }
    public void clear(){
        lbl_total.setText("");
    }
    
    /**
     * Creates new form Cetak_Laporan
     */
    public Cetak_Laporan() {
        initComponents();
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_laporan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDate1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDate2 = new com.toedter.calendar.JDateChooser();
        lbl_total = new javax.swing.JLabel();
        btnhitung = new usu.widget.ButtonGlass();
        btncari = new usu.widget.ButtonGlass();
        btncetak = new usu.widget.ButtonGlass();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_laporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        tabel_laporan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tabel_laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal Peminjaman", "Tanggal Kembali", "Peminjam", "Nopol", "Harga Sewa", "Lama Pinjam", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_laporan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1060, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("LAPORAN DATA TRANSAKSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel9.setText("FATIH");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, -1, -1));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("AL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, -1, -1));

        panelGlass2.setBackground(new java.awt.Color(255, 255, 255));
        panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        panelGlass2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("DARI TANGGAL :");
        panelGlass2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("TOTAL TRANSAKSI :");
        panelGlass2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        panelGlass2.add(jDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 150, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("SAMPAI TANGGAL :");
        panelGlass2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
        panelGlass2.add(jDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, -1));

        lbl_total.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(204, 0, 0));
        lbl_total.setText("Total");
        panelGlass2.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, 30));

        btnhitung.setForeground(new java.awt.Color(0, 51, 255));
        btnhitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-calculator-32.png"))); // NOI18N
        btnhitung.setText("HITUNG");
        btnhitung.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btnhitung.setOpaque(true);
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        panelGlass2.add(btnhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, 40));

        btncari.setBorder(new javax.swing.border.MatteBorder(null));
        btncari.setForeground(new java.awt.Color(0, 51, 255));
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/search_lense.png"))); // NOI18N
        btncari.setText("CARI");
        btncari.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btncari.setOpaque(true);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        panelGlass2.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 80, 50));

        btncetak.setForeground(new java.awt.Color(0, 51, 255));
        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-printer2-40.png"))); // NOI18N
        btncetak.setText("CETAK LAPORAN");
        btncetak.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btncetak.setOpaque(true);
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        panelGlass2.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 190, 100));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Rp.");
        panelGlass2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 40));

        getContentPane().add(panelGlass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1060, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bgputih1.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        cetak();
    }//GEN-LAST:event_btncetakActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
    // Mengambil tanggal dari komponen jDate1 dan jDate2
    java.util.Date tgl = (java.util.Date) this.jDate1.getDate();
    java.util.Date tgl1 = (java.util.Date) this.jDate2.getDate();
    // Memeriksa apakah kedua tanggal tidak kosong
    if (new java.sql.Date(tgl.getTime()).toString().isEmpty() && new java.sql.Date(tgl1.getTime()).toString().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Tanggal data pencarian masih kosong");
    } else {
    try {
        // Format tanggal ke format yang sesuai dengan query SQL
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String a = new java.sql.Date(tgl.getTime()).toString();
        String b = new java.sql.Date(tgl1.getTime()).toString();
        // Menentukan kolom yang akan diambil dari tabel
        String kolom[] = { "tgl_peminjaman", "tgl_kembali","peminjam", "nopol", "harga", "lama", "total"};
        // Membuat query SQL dengan menggunakan metode querySelect dari objek con (Database)
        rs = con.querySelect(kolom ,"tb_laporan"," DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')>='"+a+"' AND DATE_FORMAT(tgl_peminjaman,'%Y-%m-%d')<= '"+b+"' "); 
        // Menetapkan hasil query ke model tabel
        tabel_laporan.setModel(new Database.ResultSetTable(rs));
    } catch (Exception e) {
        // Menampilkan pesan kesalahan jika terjadi exception
        JOptionPane.showMessageDialog(this, "Pencarian Error");
    }
}
    // Membersihkan komponen setelah pencarian selesai
    clear();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        hitungtotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhitungActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btncari;
    private usu.widget.ButtonGlass btncetak;
    private usu.widget.ButtonGlass btnhitung;
    private com.toedter.calendar.JDateChooser jDate1;
    private com.toedter.calendar.JDateChooser jDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total;
    private usu.widget.glass.PanelGlass panelGlass2;
    private javax.swing.JTable tabel_laporan;
    // End of variables declaration//GEN-END:variables

}
