import Database.KoneksiDatabase;
import Database.ResultSetTable;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Data_Peminjam extends javax.swing.JInternalFrame {
   // Metode untuk menghapus dan me REFRESH teks dari komponen teks di dalam form
    public void clearTextFields() {
        noktp.setText("");
        nama.setText("");
        alamat.setText("");
        notelp.setText("");
        Cari.setText("");
    }
    ResultSet rs;
    KoneksiDatabase con;
    
    /**
     * Creates new form Add_Car
     */
    public Data_Peminjam() {
        initComponents();    
        con =new KoneksiDatabase(new Database.Parameter().HOST_DB,new Database.Parameter().USERNAME_DB,new Database.Parameter().PASSWORD_DB);
        loadTabel();   
        clearTextFields();
    }
    // Metode untuk memuat data peminjam dari database ke dalam tabel
    private void loadTabel() {
    // Menentukan nama kolom yang akan ditampilkan dalam tabel
    String namaKolom[] = {"id_peminjam", "noktp", "nama", "alamat", "telp"};
    // Mengambil data dari database berdasarkan nama kolom
    rs = con.querySelect(namaKolom, "tb_peminjam");
    // Menetapkan model tabel dengan hasil query dari database
    tabel_peminjam.setModel(new ResultSetTable(rs));
    }
    // Metode untuk membersihkan field-field input
    private void clear() {
    // Mengosongkan field-field input seperti noktp, nama, alamat, notelp, dan Cari
    noktp.setText("");
    nama.setText("");
    alamat.setText("");
    notelp.setText("");
    Cari.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_peminjam = new javax.swing.JTable();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        noktp = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        notelp = new javax.swing.JLabel();
        btn_back = new usu.widget.ButtonGlass();
        Cari = new javax.swing.JTextField();
        btn_cari = new usu.widget.ButtonGlass();
        btn_refresh1 = new usu.widget.ButtonGlass();
        btn_delete = new usu.widget.ButtonGlass();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 189, 122));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_peminjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        tabel_peminjam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tabel_peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Peminjam", "No KTP", "Nama", "Alamat", "No. HP"
            }
        ));
        tabel_peminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_peminjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_peminjam);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1050, 250));

        panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setText("INFORMASI DATA PEMINJAM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Karta.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("NO.KTP");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("ALAMAT");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("NAMA");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("NO.TELP");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText(":");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText(":");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText(":");

        noktp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        noktp.setForeground(new java.awt.Color(0, 51, 255));
        noktp.setText("lbl_no_ktp");

        nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 51, 255));
        nama.setText("lbl_nama");

        alamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(0, 51, 255));
        alamat.setText("lbl_alamat");

        notelp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        notelp.setForeground(new java.awt.Color(0, 51, 255));
        notelp.setText("lbl_no_telp");

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(noktp)
                            .addComponent(notelp)
                            .addComponent(alamat))
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(71, 71, 71)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(noktp))
                        .addGap(18, 18, 18)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(nama))
                        .addGap(18, 18, 18)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(alamat))
                        .addGap(41, 41, 41)
                        .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(notelp)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, 800, 280));

        btn_back.setForeground(new java.awt.Color(0, 51, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-back-40.png"))); // NOI18N
        btn_back.setText("KEMBALI");
        btn_back.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btn_back.setOpaque(true);
        btn_back.setRoundRect(true);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, -1));

        Cari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Cari.setForeground(new java.awt.Color(0, 51, 255));
        Cari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kGradientPanel1.add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 414, 970, -1));

        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_lense.png"))); // NOI18N
        btn_cari.setRoundRect(true);
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 71, -1));

        btn_refresh1.setForeground(new java.awt.Color(0, 51, 255));
        btn_refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-refresh-40 (1).png"))); // NOI18N
        btn_refresh1.setText("Refresh");
        btn_refresh1.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btn_refresh1.setOpaque(true);
        btn_refresh1.setRoundRect(true);
        btn_refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_refresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 160, -1));

        btn_delete.setForeground(new java.awt.Color(0, 51, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-delete-40.png"))); // NOI18N
        btn_delete.setText("HAPUS");
        btn_delete.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        btn_delete.setOpaque(true);
        btn_delete.setRoundRect(true);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 140, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/bgputih1.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
    try {
        // Mengambil nilai ID dari baris yang dipilih di tabel
        String id = String.valueOf(tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(), 0));
        // Konfirmasi pengguna untuk menghapus data
        int option = JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            // Melakukan penghapusan data jika pengguna menekan tombol OK
            con.queryDelete("tb_peminjam", "id_peminjam=" + id);
        } else {
            // Kembali jika pengguna membatalkan penghapusan
            return;
        }
    } catch (Exception e) {
        // Menampilkan pesan kesalahan jika tidak ada baris yang dipilih
        JOptionPane.showMessageDialog(this, "Pilih ID terlebih dahulu");
    }
    // Memuat ulang tabel setelah penghapusan data
    loadTabel();
    // Membersihkan input setelah penghapusan data
    clear();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh1ActionPerformed
        loadTabel();
        clearTextFields();
    }//GEN-LAST:event_btn_refresh1ActionPerformed

    private void tabel_peminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_peminjamMouseClicked
        //.setText(String.valueOf(tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),0)));
        noktp.setText(String.valueOf(tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),1)));
        nama.setText(String.valueOf( tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),2)));
        alamat.setText(String.valueOf(tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),3)));
        notelp.setText(String.valueOf( tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),4)));
        //txt_harga.setText(String.valueOf( tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),5)));
        //c_Status.setSelectedItem(String.valueOf(tabel_peminjam.getValueAt(tabel_peminjam.getSelectedRow(),6)));
    }//GEN-LAST:event_tabel_peminjamMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
    // Memeriksa apakah field pencarian kosong
    if (Cari.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isikan data pencarian");
    } else {
        try {
            // Menyiapkan array kolom yang akan dicari
            String kolom[] = {"id_peminjam", "noktp", "nama"};
            // Melakukan query pencarian dengan menggunakan fungsi querySelectAll
            rs = con.querySelectAll("tb_peminjam", 
                "id_peminjam LIKE '%" + Cari.getText() + "%' OR " +
                "noktp LIKE '%" + Cari.getText() + "%' OR " +
                "nama LIKE '%" + Cari.getText() + "%'");
            // Menetapkan model tabel dengan hasil pencarian
            tabel_peminjam.setModel(new Database.ResultSetTable(rs));
        } catch (Exception e) {
            // Menangani exception yang mungkin terjadi selama proses pencarian
            JOptionPane.showMessageDialog(this, "Pencarian Error");
        }
    }
    // Membersihkan field pencarian setelah proses pencarian
    clear();
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
    // Menghapus semua komponen yang ada di jDesktopPane1 pada frame Home
    Home.jDesktopPane1.removeAll();
    // Melakukan repaint (menggambar ulang) jDesktopPane1
    Home.jDesktopPane1.repaint();
    // Membuat objek Form_Pengembalian
    Form_Pengembalian fp = new Form_Pengembalian();
    // Menampilkan Form_Pengembalian
    fp.setVisible(true);
    // Menambahkan Form_Pengembalian ke jDesktopPane1 pada frame Home
    Home.jDesktopPane1.add(fp);
    }//GEN-LAST:event_btn_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cari;
    private javax.swing.JLabel alamat;
    private usu.widget.ButtonGlass btn_back;
    private usu.widget.ButtonGlass btn_cari;
    private usu.widget.ButtonGlass btn_delete;
    private usu.widget.ButtonGlass btn_refresh1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel noktp;
    private javax.swing.JLabel notelp;
    private usu.widget.glass.PanelGlass panelGlass1;
    private javax.swing.JTable tabel_peminjam;
    // End of variables declaration//GEN-END:variables
  
}
